name: minecraft-rpg
version: 1.0-SNAPSHOT
main: br.com.rafaelfaustini.minecraftrpg.MinecraftRpg
authors: [RafaelFaustini, RaphaelBaruffi]
commands:
  class:
    description: Choose your primary class!
    usage: /<command>
